name: Selenium Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip libxss1

    - name: Install Chrome
      run: |
        wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install ./google-chrome-stable_current_amd64.deb -y --allow-downgrades --fix-missing
        sudo rm google-chrome-stable_current_amd64.deb
        echo "Chrome version: $(google-chrome --version)"

    - name: Install ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
        CHROME_MAJOR_VERSION=${CHROME_VERSION%.*.*}
        wget -q https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_MAJOR_VERSION}
        CHROMEDRIVER_VERSION=$(cat LATEST_RELEASE_${CHROME_MAJOR_VERSION})
        wget -q https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
        echo "ChromeDriver version: $(chromedriver --version)"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest==7.4.0 selenium==4.15.2 webdriver-manager==4.0.1 pytest-html==4.1.1

    - name: Verify environment
      run: |
        python -c "import pytest; print(f'Pytest version: {pytest.__version__}')"
        python -c "from selenium import webdriver; print('Selenium imports successfully')"
        python -c "import conftest; print('Conftest imports successfully')"

    - name: Run tests
      run: |
        python -m pytest tests/test_02_login.py -v --html=test-reports/report.html
      env:
        DISPLAY: ":99"

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: test-reports/